server:
  port: 8080

nettyrpc:
  client:
    enable: true
  serviceId: nettyrpc-server
  registryAddress: list://127.0.0.1:18080
#  registryAddress: file://conf/server_list.conf
#  registryAddress: nacos://127.0.0.1:8848
#  registryAddress: consul://127.0.0.1:8500
  protocolType: 1
  loadBalanceType: 1