server:
  port: 8081

#registry:
#  center:
#    address: list://127.0.0.1:18866

nettyrpc:
  client:
    enable: true
  registryAddress: list://127.0.0.1:18080
  protocolType: 2
#  loadBalanceType: 0