server:
  port: 8081

#registry:
#  center:
#    address: list://127.0.0.1:18866

nettyrpc:
  client:
    enable: true
  registryAddress: nacos://127.0.0.1:8848
  serviceId: nettyrpc-server
#  registryAddress: list://127.0.0.1:18080,127.0.0.1:18081
#  registryAddress: file://conf/server_list.conf
  protocolType: 1
  loadBalanceType: 0